Resolve references hooks
aws-controllers-k8s/code-generator pull request #294
Opened 2022-02-18 02:35 UTC by vijtrip2

Issue #, if available: https://github.com/aws-controllers-k8s/community/issues/1180

Description of changes:
* This patch adds support for two custom hooks "pre_resolve_references" and "post_resolve_references"
* These hooks are needed to support TargetRef inside APIGatewayv2 Route resource where "integrations/" prefix is added before the referred IntegrationID.
* This patch also sets ResourceSynced condition to false when LateInitialization fails. This will help remove custom ResourceSynced condition handling inside `reconciler.go`

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-02-22 12:04 UTC, A-Hilaly approved these changes
👍

2022-02-23 15:38 UTC, jaypipes requested changes
One tiny renaming request :)

2022-02-23 17:20 UTC, jaypipes approved these changes
:+1:

2022-02-23 17:20 UTC, jaypipes commented
/lgtm

2022-02-23 17:21 UTC, merged