Set `defaultResyncPeriod` helm value to 36000
aws-controllers-k8s/code-generator pull request #450
Opened 2023-05-20 02:05 UTC by A-Hilaly

Fixes https://github.com/aws-controllers-k8s/community/issues/1671

The 0 value of `defaultResyncPeriod` causes the controller to use 10
hours as a `resyncPeriod` .. which is a very confusing.

This patch sets the default value to 36000 (10 hours in seconds) to
match the expected default behaviour.

See https://github.com/aws-controllers-k8s/runtime/blob/main/pkg/runtime/reconciler.go#L48-L51

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-05-20 02:29 UTC, A-Hilaly commented
/retest

2023-05-20 03:24 UTC, A-Hilaly commented
/retest

2023-05-25 21:38 UTC, jljaco approved these changes

2023-05-26 20:31 UTC, RedbackThomson requested changes

2023-05-26 20:31 UTC, RedbackThomson commented on templates/helm/values.yaml.tpl
> +  defaultResyncPeriod: 36000 # 10 Hours (https://github.com/aws-controllers-k8s/runtime/blob/main/pkg/runtime/reconciler.go#L48-L51)
I would leave out the link to the code. It's not relevant to most customers who simply consume the default values.

2023-06-14 11:44 UTC, jaypipes commented
Note that the API Gateway test will continue to fail until https://github.com/aws-controllers-k8s/community/issues/1825 is addressed

2023-06-15 14:45 UTC, A-Hilaly commented
/retest

2023-06-15 16:20 UTC, RedbackThomson approved these changes
/lgtm

2023-06-15 16:21 UTC, merged