Namespace scope service controllers
aws-controllers-k8s/code-generator pull request #60
Opened 2021-05-11 18:50 UTC by akartsky

Add ability to listen to specific namespace for service controllers
Tested locally for both positive and negative case

aws-controllers-k8s/community#686

Related PR:
https://github.com/aws-controllers-k8s/runtime/pull/12

2021-05-11 19:17 UTC, surajkota approved these changes

2021-05-11 19:42 UTC, RedbackThomson commented
Regarding our discussion for ClusterRole and scope issues: https://github.com/aws-controllers-k8s/community/issues/770

2021-05-12 11:11 UTC, A-Hilaly commented
Can we make support watching multiple namespaces at once instead of only one?

2021-05-12 20:18 UTC, akartsky commented
> Can we support watching multiple namespaces at once instead of only one?


Yes i need to spend more time on this 

This is just a quick PR to have the feature out

2021-05-13 18:42 UTC, A-Hilaly approved these changes

2021-05-14 01:24 UTC, jaypipes approved these changes
:+1: 

good to merge after the associated runtime PR merges.

2021-05-14 01:30 UTC, jaypipes requested changes
@akartsky please update the go.mod to point to the just-curt v0.2.0 release of runtime:

https://github.com/aws-controllers-k8s/runtime/releases/tag/v0.2.0

2021-05-14 01:37 UTC, jaypipes approved these changes

2021-05-14 01:37 UTC, jaypipes commented on go.mod
> +	github.com/aws-controllers-k8s/runtime v0.2.0
:+1:

2021-05-14 01:37 UTC, merged